# Generated by Django 5.2.16 on 2026-08-03 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('project_type', models.CharField(choices=[('individuel', 'Individuel'), ('collaboratif', 'Collaboratif')], default='collaboratif', max_length=20)),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé')], default='actif', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('critique', 'Critique')], max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('chef_de_projet', 'Chef de projet'), ('membre', 'Membre')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Retirée')], default='active', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('project', 'user', 'role'), name='uniq_active_project_user_role')],
            },
        ),
    ]
