# Generated by Django 5.2.16 on 2026-08-04 15:15

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='projectmembership',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='projectmembership',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
