# Generated by Django 5.2.16 on 2026-08-04 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_require_organisation'),
        ('projects', '0004_project_notepad_content_project_notepad_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='accounts.organisation'),
        ),
    ]
