# Generated by Django 5.2.16 on 2026-08-04 20:18

from django.db import migrations


def backfill_organisation(apps, schema_editor):
    # Sûr uniquement parce que cette migration s'exécute juste après la
    # migration de données accounts (0005_backfill_organisation), qui garantit
    # qu'exactement une Organisation existe à ce stade du déploiement initial.
    Organisation = apps.get_model("accounts", "Organisation")
    Project = apps.get_model("projects", "Project")

    organisation = Organisation._base_manager.first()
    if organisation is not None:
        Project._base_manager.filter(organisation__isnull=True).update(organisation=organisation)


def noop_reverse(apps, schema_editor):
    """Pas de retour en arrière significatif — voir accounts/migrations/0005."""


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_organisation'),
        ('accounts', '0005_backfill_organisation'),
    ]

    operations = [
        migrations.RunPython(backfill_organisation, noop_reverse),
    ]
