# Generated by Django 5.2.16 on 2026-08-04 20:21

import apps.accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_team_organisation_alter_user_organisation'),
        ('projects', '0007_require_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organisation',
            field=models.ForeignKey(default=apps.accounts.models.default_organisation_id, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='accounts.organisation'),
        ),
    ]
