# Generated by Django 5.2.16 on 2026-08-05 20:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_rename_archive_to_cloture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='spec_content',
        ),
        migrations.RemoveField(
            model_name='project',
            name='spec_updated_at',
        ),
        migrations.CreateModel(
            name='SpecSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_key', models.CharField(choices=[('contexte', 'Contexte'), ('objectifs', 'Objectifs'), ('besoin', 'Besoin'), ('perimetre', 'Périmètre'), ('exigences_fonctionnelles', 'Exigences fonctionnelles'), ('exigences_techniques', 'Exigences techniques'), ('contraintes', 'Contraintes'), ('livrables', 'Livrables'), ('planning', 'Planning'), ('budget', 'Budget'), ('organisation', 'Organisation'), ('annexes', 'Annexes')], max_length=40)),
                ('is_active', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spec_sections', to='projects.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'section_key'), name='uniq_project_spec_section')],
            },
        ),
    ]
