# Generated by Django 5.2.16 on 2026-09-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_project_spec_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='already_in_production',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('chef_de_projet', 'Chef de projet'), ('membre', 'Membre'), ('lecteur', 'Lecteur')], max_length=20),
        ),
    ]
