# Generated by Django 5.2.16 on 2026-08-03 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('task_type', models.CharField(choices=[('correction', 'Correction'), ('ajout', 'Ajout'), ('evolution', 'Évolution')], max_length=20)),
                ('priority', models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('critique', 'Critique')], default='moyenne', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('time_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('origin', models.CharField(choices=[('manuelle', 'Manuelle'), ('api', 'API')], default='manuelle', max_length=20)),
                ('external_reference_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('en_attente_validation', 'En attente de validation'), ('disponible', 'Disponible'), ('assignee', 'Assignée'), ('en_cours', 'En cours'), ('rejetee', 'Rejetée'), ('archivee', 'Archivée')], default='en_attente_validation', max_length=30)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
