# Generated by Django 5.2.16 on 2026-08-05 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_status_projectversion'),
        ('tasks', '0002_alter_task_options_alter_task_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='projects.projectversion'),
        ),
    ]
