# Generated by Django 5.2.16 on 2026-09-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_estimated_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('correction', 'Correction'), ('ajout', 'Ajout'), ('evolution', 'Évolution'), ('test', 'Test')], max_length=20),
        ),
    ]
