# Generated by Django 5.2.16 on 2026-09-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('en_attente_validation', 'En attente de validation'), ('disponible', 'Disponible'), ('assignee', 'Assignée'), ('en_cours', 'En cours'), ('rejetee', 'Rejetée'), ('archivee', 'Archivée'), ('annulee', 'Annulée')], default='en_attente_validation', max_length=30),
        ),
    ]
