# Generated by Django 5.2.16 on 2026-10-09 07:08

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_permissionprofile_user_permission_profiles'),
        ('projects', '0012_project_already_in_production_and_more'),
        ('tasks', '0009_task_cancellation_reason_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=50)),
                ('icon', models.CharField(choices=[('wrench', 'Clé'), ('circle_plus', 'Plus'), ('trending_up', 'Flèche montante'), ('flask', 'Fiole'), ('rocket', 'Fusée'), ('code', 'Code'), ('lightbulb', 'Ampoule'), ('book', 'Livre'), ('search', 'Loupe'), ('bug', 'Bug'), ('file', 'Document'), ('users', 'Personnes'), ('shield', 'Bouclier'), ('tag', 'Étiquette')], default='tag', max_length=30)),
                ('position', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('archived', 'Archivé')], default='active', max_length=20)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_types', to='projects.project')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_types', to='accounts.team')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('team', 'key'), name='unique_task_type_key_per_team'), models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('project', 'key'), name='unique_task_type_key_per_project')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
