# Generated by Django 5.2.16 on 2026-08-04 20:16

from django.db import migrations

# Migration de données (voir CLAUDE.md > "Organisation" > "Migration de
# données") : crée une organisation unique et y rattache tous les User/Team
# existants. Désigne un utilisateur organisation_role=admin ET
# is_platform_admin=True — sans ça personne ne peut administrer quoi que ce
# soit après cette passe. Choix arbitraire mais documenté (pas de "compte de
# test principal" identifiable dans l'historique) : le premier utilisateur
# par date de création (généralement le compte de démo créé en premier via
# `seed_demo_users`) — à corriger manuellement si ce n'est pas le bon compte.
ORGANISATION_NAME = "Répar'Stores"


def backfill_organisation(apps, schema_editor):
    Organisation = apps.get_model("accounts", "Organisation")
    Team = apps.get_model("accounts", "Team")
    User = apps.get_model("accounts", "User")

    organisation, _ = Organisation._base_manager.get_or_create(name=ORGANISATION_NAME)

    Team._base_manager.filter(organisation__isnull=True).update(organisation=organisation)
    User._base_manager.filter(organisation__isnull=True).update(organisation=organisation)

    first_user = User._base_manager.order_by("date_joined", "username").first()
    if first_user is not None:
        first_user.organisation_role = "admin"
        first_user.is_platform_admin = True
        first_user.save(update_fields=["organisation_role", "is_platform_admin"])


def noop_reverse(apps, schema_editor):
    """Pas de retour en arrière significatif : on ne supprime jamais de
    données (règle transverse), et il n'y a rien d'autre à défaire — les
    lignes User/Team gardent leur organisation, ce qui reste cohérent même
    si cette migration est retirée."""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organisation_team_created_by_user_is_platform_admin_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_organisation, noop_reverse),
    ]
