# Generated by Django 5.2.16 on 2026-08-04 20:21

import apps.accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_require_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='organisation',
            field=models.ForeignKey(default=apps.accounts.models.default_organisation_id, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='accounts.organisation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(default=apps.accounts.models.default_organisation_id, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.organisation'),
        ),
    ]
