# Generated by Django 5.2.16 on 2026-08-04 20:26

from django.db import migrations


def backfill_team_membership(apps, schema_editor):
    # `team.members` (le M2M brut) existe encore à ce stade de la migration —
    # supprimé juste après (voir migration suivante), une fois ces lignes
    # converties en TeamMembership.
    Team = apps.get_model("accounts", "Team")
    TeamMembership = apps.get_model("accounts", "TeamMembership")

    for team in Team._base_manager.all():
        for user in team.members.all():
            TeamMembership._base_manager.get_or_create(team=team, user=user, defaults={"status": "active"})


def noop_reverse(apps, schema_editor):
    """Pas de retour en arrière significatif — voir accounts/migrations/0005."""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_teammembership'),
    ]

    operations = [
        migrations.RunPython(backfill_team_membership, noop_reverse),
    ]
