# Generated by Django 5.2.16 on 2026-08-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_backfill_team_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
    ]
