# Generated by Django 5.2.16 on 2026-09-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='role',
            field=models.CharField(choices=[('membre', 'Membre'), ('administrateur', 'Administrateur')], default='membre', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('desactive', 'Désactivé')], default='active', max_length=20),
        ),
    ]
