# Generated by Django 5.2.16 on 2026-09-18 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_teammembership_role_user_email_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='planning_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='work_hours_end',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='user',
            name='work_hours_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
