# Generated by Django 5.2.16 on 2026-09-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_planning_color_user_work_hours_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='work_hours_end',
        ),
        migrations.RemoveField(
            model_name='user',
            name='work_hours_start',
        ),
    ]
