# Generated by Django 5.2.16 on 2026-09-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_user_work_hours_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='outlook_calendar_sync_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
