# Generated by Django 5.2.16 on 2026-09-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_outlook_calendar_sync_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accent_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
