# Generated by Django 5.2.16 on 2026-09-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_accent_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accent_color',
        ),
        migrations.AddField(
            model_name='organisation',
            name='brand_primary_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='organisation',
            name='brand_secondary_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
