# Generated by Django 5.2.16 on 2026-10-01 11:07

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0012_project_already_in_production_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('projet', 'Projet'), ('global', 'Global')], max_length=10)),
                ('widget_type', models.CharField(choices=[('defaut', 'Par défaut'), ('personnalise', 'Personnalisé')], max_length=20)),
                ('metric_key', models.CharField(blank=True, default='', max_length=60)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('visibility', models.CharField(choices=[('individuel', 'Individuel'), ('groupe', 'Groupe')], default='individuel', max_length=10)),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('x', models.PositiveIntegerField(default=0)),
                ('y', models.PositiveIntegerField(default=0)),
                ('w', models.PositiveIntegerField(default=4)),
                ('h', models.PositiveIntegerField(default=3)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('removed', 'Retiré')], default='active', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_widgets', to='projects.project')),
            ],
            options={
                'ordering': ['y', 'x'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['owner', 'scope', 'project'], name='dashboards__owner_i_72ced5_idx')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
