# Generated by Django 5.2.16 on 2026-09-08 11:38

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0006_incident_assigned_to'),
        ('projects', '0011_remove_project_spec_content_and_more'),
        ('tasks', '0007_task_estimated_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('recurrence_rule', models.TextField(blank=True, default='')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('confirme', 'Confirmé'), ('annule', 'Annulé')], default='confirme', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPlanningEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('recurrence_rule', models.TextField(blank=True, default='')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('jalon', 'Jalon'), ('phase', 'Phase'), ('reunion', 'Réunion'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('status', models.CharField(choices=[('confirme', 'Confirmé'), ('annule', 'Annulé')], default='confirme', max_length=20)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_planning_entries', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_entries', to='projects.project')),
            ],
            options={
                'ordering': ['start'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CalendarShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Révoquée')], default='active', max_length=20)),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_shares_received', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_shares_granted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('owner', 'grantee'), name='uniq_active_calendar_share'), models.CheckConstraint(condition=models.Q(('owner', models.F('grantee')), _negated=True), name='calendarshare_owner_not_grantee')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.CharField(choices=[('invite', 'Invité'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='invite', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Retirée')], default='active', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='planning.calendarevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('event', 'user'), name='uniq_active_event_participant')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('planifie', 'Planifié'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_blocks', to='incidents.incident')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_blocks', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_blocks', to='tasks.task')),
            ],
            options={
                'ordering': ['start'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('incident__isnull', True), ('task__isnull', False)), models.Q(('incident__isnull', False), ('task__isnull', True)), _connector='OR'), name='scheduledblock_exactly_one_target')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
