# Generated by Django 5.2.16 on 2026-09-18 13:19

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarshare',
            name='can_manage_work_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WorkingHoursWeekOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['week_start'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHoursOverrideDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('enabled', models.BooleanField(default=True)),
                ('start', models.TimeField(default=datetime.time(9, 0))),
                ('end', models.TimeField(default=datetime.time(18, 0))),
                ('override', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='planning.workinghoursweekoverride')),
            ],
            options={
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHoursDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('enabled', models.BooleanField(default=True)),
                ('start', models.TimeField(default=datetime.time(9, 0))),
                ('end', models.TimeField(default=datetime.time(18, 0))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['weekday'],
                'constraints': [models.UniqueConstraint(fields=('user', 'weekday'), name='uniq_working_hours_day')],
            },
        ),
        migrations.AddConstraint(
            model_name='workinghoursweekoverride',
            constraint=models.UniqueConstraint(fields=('user', 'week_start'), name='uniq_working_hours_week_override'),
        ),
        migrations.AddConstraint(
            model_name='workinghoursoverrideday',
            constraint=models.UniqueConstraint(fields=('override', 'weekday'), name='uniq_working_hours_override_day'),
        ),
    ]
