# Generated by Django 5.2.16 on 2026-09-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_calendarshare_can_manage_work_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='outlook_event_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
