# Generated by Django 5.2.16 on 2026-09-23 07:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_calendarevent_outlook_event_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockOutlookSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlook_event_id', models.CharField(blank=True, default='', max_length=200)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlook_syncs', to='planning.scheduledblock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('block', 'user'), name='blockoutlooksync_unique_block_user')],
            },
        ),
    ]
