# Generated by Django 5.2.16 on 2026-09-23 08:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_blockoutlooksync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledblock',
            name='outlook_event_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='EventParticipantOutlookSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlook_event_id', models.CharField(blank=True, default='', max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_outlook_syncs', to='planning.calendarevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BlockOutlookSync',
        ),
        migrations.AddConstraint(
            model_name='eventparticipantoutlooksync',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='eventparticipantoutlooksync_unique_event_user'),
        ),
    ]
