# Generated by Django 5.2.16 on 2026-09-23 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_scheduledblock_outlook_event_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEventOccurrenceOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_start', models.DateTimeField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_overrides', to='planning.calendarevent')),
            ],
            options={
                'ordering': ['original_start'],
            },
        ),
        migrations.CreateModel(
            name='EventOccurrenceOutlookSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlook_event_id', models.CharField(blank=True, default='', max_length=200)),
                ('override', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlook_syncs', to='planning.calendareventoccurrenceoverride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='calendareventoccurrenceoverride',
            constraint=models.UniqueConstraint(fields=('event', 'original_start'), name='eventoccurrenceoverride_unique_event_original_start'),
        ),
        migrations.AddConstraint(
            model_name='eventoccurrenceoutlooksync',
            constraint=models.UniqueConstraint(fields=('override', 'user'), name='eventoccurrenceoutlooksync_unique_override_user'),
        ),
    ]
