# Generated by Django 5.2.16 on 2026-09-10 16:09

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_passwordresetrequest'),
        ('incidents', '0007_incident_author_email_incident_author_name'),
        ('projects', '0012_project_already_in_production_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_type', models.CharField(choices=[('email', 'Adresse mail'), ('teams', 'Canal Teams')], max_length=10)),
                ('label', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('teams_webhook_url', models.URLField(blank=True, default='')),
                ('notify_incident_created', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('archived', 'Archivé')], default='active', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_channels', to='projects.project')),
            ],
            options={
                'ordering': ['channel_type', 'label'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('trigger', models.CharField(choices=[('manuel', 'Manuel'), ('incident_cree', "Création d'incident")], default='manuel', max_length=20)),
                ('status', models.CharField(choices=[('en_attente', "En attente d'envoi"), ('envoye', 'Envoyé'), ('echec', 'Échec')], default='en_attente', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('channels', models.ManyToManyField(related_name='messages', to='communication.communicationchannel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_communications', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communications', to='incidents.incident')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_messages', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='O365Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, default='', max_length=100)),
                ('client_id', models.CharField(blank=True, default='', max_length=100)),
                ('client_secret', models.CharField(blank=True, default='', max_length=255)),
                ('sender_mailbox', models.EmailField(blank=True, default='', max_length=254)),
                ('is_enabled', models.BooleanField(default=False)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='o365_connection', to='accounts.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
