# Generated by Django 5.2.16 on 2026-09-28 08:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationchannel',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'all_objects', 'ordering': ['label']},
        ),
        migrations.RemoveField(
            model_name='communicationchannel',
            name='channel_type',
        ),
        migrations.RemoveField(
            model_name='communicationchannel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='o365connection',
            name='sender_mailbox',
        ),
        migrations.AddField(
            model_name='communicationchannel',
            name='teams_channel_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='communicationchannel',
            name='teams_channel_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.CreateModel(
            name='CommunicationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('en_attente', "En attente d'envoi"), ('envoye', 'Envoyé'), ('echec', 'Échec')], default='en_attente', max_length=20)),
                ('response_detail', models.TextField(blank=True, default='')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='communication.communicationchannel')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='communication.communicationmessage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='communicationmessage',
            name='channels',
        ),
        migrations.AddField(
            model_name='communicationmessage',
            name='channels',
            field=models.ManyToManyField(related_name='messages', through='communication.CommunicationDelivery', to='communication.communicationchannel'),
        ),
        migrations.AddConstraint(
            model_name='communicationdelivery',
            constraint=models.UniqueConstraint(fields=('message', 'channel'), name='unique_delivery_per_message_channel'),
        ),
    ]
