# Generated by Django 5.2.16 on 2026-09-28 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_alter_communicationchannel_options_and_more'),
        ('tasks', '0009_task_cancellation_reason_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationchannel',
            name='payload_template',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='communicationmessage',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communications', to='tasks.task'),
        ),
    ]
