# Generated by Django 5.2.16 on 2026-10-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_communicationchannel_payload_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationchannel',
            name='teams_webhook_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
