# Generated by Django 5.2.16 on 2026-10-07 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_permissionprofile_user_permission_profiles'),
        ('communication', '0004_alter_communicationchannel_teams_webhook_url'),
        ('projects', '0012_project_already_in_production_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationchannel',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communication_channels', to='accounts.team'),
        ),
        migrations.AlterField(
            model_name='communicationchannel',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communication_channels', to='projects.project'),
        ),
    ]
