# Generated by Django 5.2.16 on 2026-09-03 14:37

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0006_incident_assigned_to'),
        ('projects', '0011_remove_project_spec_content_and_more'),
        ('tasks', '0007_task_estimated_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocSpace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('public_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='doc_space', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('fonctionnalite', 'Fonctionnalité'), ('resolution', "Résolution d'incident")], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('manuelle', 'Manuelle'), ('tache', 'Tâche'), ('incident', 'Incident'), ('cahier_des_charges', 'Cahier des charges')], default='manuelle', max_length=30)),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('source_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_entries', to='incidents.incident')),
                ('source_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_entries', to='tasks.task')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='documentation.docspace')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DocPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('content', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='documentation.docpage')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='documentation.docspace')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'archive'), _negated=True), fields=('space', 'slug'), name='uniq_active_docpage_slug_per_space')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PendingDocEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('fonctionnalite', 'Fonctionnalité'), ('resolution', "Résolution d'incident")], max_length=20)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('traitee', 'Traitée'), ('ignoree', 'Ignorée')], default='en_attente', max_length=20)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documentation.docentry')),
                ('incident', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doc_pending_entry', to='incidents.incident')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pending_entries', to='documentation.docspace')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doc_pending_entry', to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('incident__isnull', True), ('task__isnull', False)), models.Q(('incident__isnull', False), ('task__isnull', True)), _connector='OR'), name='pendingdocentry_exactly_one_source')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
