# Generated by Django 5.2.16 on 2026-09-23 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
        ('projects', '0012_project_already_in_production_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentry',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_entries', to='projects.projectversion'),
        ),
        migrations.AddField(
            model_name='docspace',
            name='accent_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='docspace',
            name='custom_slug',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='docspace',
            name='footer_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='docspace',
            name='header_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='docentry',
            name='kind',
            field=models.CharField(choices=[('fonctionnalite', 'Fonctionnalité'), ('resolution', "Résolution d'incident"), ('contributeurs', 'Contributeurs au projet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingdocentry',
            name='kind',
            field=models.CharField(choices=[('fonctionnalite', 'Fonctionnalité'), ('resolution', "Résolution d'incident"), ('contributeurs', 'Contributeurs au projet')], max_length=20),
        ),
    ]
