# Generated by Django 5.2.16 on 2026-08-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0002_budgetline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetline',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
