# Generated by Django 5.2.16 on 2026-08-03 14:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('critique', 'Critique')], default='moyenne', max_length=20)),
                ('status', models.CharField(choices=[('signale', 'Signalé'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('archive', 'Archivé')], default='signale', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
