# Generated by Django 5.2.16 on 2026-08-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='external_reference_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
