# Generated by Django 5.2.16 on 2026-08-06 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_account_status_user_account_type_invitation'),
        ('incidents', '0004_incidentcomment'),
        ('projects', '0011_remove_project_spec_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='accounts.team'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='projects.project'),
        ),
    ]
