# Generated by Django 5.2.16 on 2026-09-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_incident_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='author_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='incident',
            name='author_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
