# Generated by Django 5.2.16 on 2026-09-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_incident_author_email_incident_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='resolution_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='time_spent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
