# Generated by Django 5.2.16 on 2026-09-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_incident_resolution_comment_incident_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('signale', 'Signalé'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('archive', 'Archivé'), ('annule', 'Annulé')], default='signale', max_length=20),
        ),
    ]
