# Generated by Django 5.2.16 on 2026-09-08 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='planning.calendarevent'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('task_assigned', 'Tâche assignée'), ('task_commented', 'Commentaire sur une tâche'), ('incident_commented', 'Commentaire sur un incident'), ('event_invited', 'Invitation à un événement')], max_length=30),
        ),
    ]
